name: Workflow Run Based on "events.yml"
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was trigered because 'Repository Events' was completed!"